In [2]:
!pip install numpy
!pip install scipy
!pip install scikit-learn
!pip install pandas


In [3]:
import numpy as np

In [4]:
arr = np.array([1,4,9])
arr

array([1, 4, 9])

In [5]:
print(arr*2)
print(arr*arr)

[ 2  8 18]
[ 1 16 81]


In [6]:
print(np.average(arr),np.min(arr),np.max(arr))

4.66666666667 1 9


In [7]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849])

In [8]:
np.diff(arr)

array([3, 5])

In [9]:
np.random.randn(100)

array([-0.86929956, -1.90923836,  0.0483562 , -1.40619573, -0.40086159,
        0.07769516,  0.88443153,  0.97109691,  1.51571305,  0.51805783,
       -1.21142007, -1.7332942 ,  0.12614607, -0.77362719,  0.33205732,
        0.9722988 ,  0.52312884, -0.12369854,  0.02603646, -0.36677654,
       -0.34918351, -0.03053965, -0.58278806,  1.842246  , -0.69546624,
       -0.39291032,  0.88972114, -0.87750834, -0.08564519,  0.51800938,
       -0.60380199, -0.45095785, -2.44852603,  0.78489925, -1.73259537,
        0.39248694, -0.62742194, -0.2772183 ,  1.25160833,  0.72982457,
       -1.43411813, -1.2282633 , -2.42811795,  1.62870444,  0.92549901,
       -0.92291595,  0.39936111, -1.77104127, -0.43419296,  0.04942171,
        0.29958921, -0.82219833, -1.392764  ,  0.29130574, -1.1977754 ,
       -0.89996488, -0.41820971,  0.4695465 ,  0.0946487 ,  0.02166867,
       -0.64347482,  0.20130238, -1.08571943,  0.55518878,  0.02574431,
        0.49186351,  0.85471125,  0.67318451,  0.41263017,  0.25

In [10]:
arange = np.arange(0,10,1)
arange 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
2**arange

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [12]:
arange.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
import scipy.stats as stats

https://docs.scipy.org/doc/scipy/reference/stats.html

In [ ]:
import pandas as pd

https://pandas.pydata.org/pandas-docs/stable/10min.html

1+1

Hello! 

In [1]:
def test(x):
    print(x)
    return x
    
test(2)

2


2